


### GET
GET http://127.0.0.1:8080/rum/binding?name=zhangsan&password=zhangsan123




### GET
GET http://127.0.0.1:8080/rum/binding


### create user
POST http://127.0.0.1:8080/rum/create-user?sleep=5
Content-Type: application/json

{
    "name":"zhangsan",
    "password":"zhangsan123"
}


### create user
POST http://127.0.0.1:8080/rum/create-user?sleep=3
Content-Type: application/json

{
    "name":"wangwu",
    "password":"wangwu123"
}


